version: "3.1"

services:
  app:
    container_name: php-apache-ssl
    build:
      context: .
      dockerfile: Dockerfile.local
    image: application
    volumes:
      - ./:/var/www/html
    ports:
      - 8082:80
      - 443:443